name: school
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  intl: ^0.16.1
  firebase_storage: ^4.0.1
  syncfusion_flutter_calendar: ^18.3.40
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^4.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
